### ISSUE TITLE
Don't map to DB if `survey_type='practice'`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#105]
## Request
If `body.survey_type`=== `'practice'`, stop flow and log message `Test 'practice' survey. Not uploading data to database.`. 

If `body.survey_type`=== 'real'` or is `undefined, proceed with the job as usual. 

## expression
1. https://github.com/OpenFn/ConSoSci/blob/master/bns/survey.js
2. https://github.com/OpenFn/ConSoSci/blob/master/bns/price.js
3. https://github.com/OpenFn/ConSoSci/blob/master/ngrt/2019.js
4. https://github.com/OpenFn/ConSoSci/blob/master/vegetation/VegetationClassficationAndTreeMeasurementForm.js
5. https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js

## state
DB: WCS Programs
1. https://www.openfn.org/projects/p5x4g4/messages/mpq5m76z
2. https://www.openfn.org/projects/p5x4g4/messages/mwbg768q
3. https://www.openfn.org/projects/p5x4g4/messages/m63vwb9j
4. https://www.openfn.org/projects/p5x4g4/messages/m3pzqz8n
5. https://www.openfn.org/projects/p5x4g4/messages/mj45z5z4

## adaptor
mssql

**Comment by taylordowns2000** [comment]
@aleksa-krolls , this can now be addressed via `exclusion` criteria for message filter triggers:
- https://docs.openfn.org/documentation/build/triggers#message-filter-triggers
- https://docs.openfn.org/documentation/build/triggers#message-filter-triggers
- https://docs.openfn.org/documentation/release-notes#version-19244-2021-05-07

See slack thread for questions about testing on staging and if/when to deploy to prod: https://openfn.slack.com/archives/G2LJCFFDW/p1620388180012200

**Comment by taylordowns2000** [comment]
Rather than updating the jobs, i've made updates to the 5 triggers to use "exclusion filters", a new OpenFn/platform feature:
- https://openfn.org/projects/p5x4g4/triggers/tyewax - bns/survey
- https://openfn.org/projects/p5x4g4/triggers/ty4gg5 - bns/price
- https://openfn.org/projects/p5x4g4/triggers/t9p66p - NRGT 2019
- https://openfn.org/projects/p5x4g4/triggers/t9jxxe - veg
- https://openfn.org/projects/p5x4g4/triggers/t9vjw8 - arcadia
