### ISSUE TITLE
Change `text` column type support `unicode`

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/ConSoSci#123]
## Describe the bug
In the automation solution, `text` type DB columns need to handle `unicode` characters. Let's switch to a column data type (`nvarchar`?) that supports `unicode`.

Job to update: 
https://github.com/OpenFn/ConSoSci/blob/4f0b97a9d58434272e5177194b6247a062380dbd/automation/01-processForm.js#L21-L35

### state.json

See LP for `OpenFn Kobo`, `WCS ConSoSci DB (postgres)`, and `WCS Test Mssql DB`
You can use job 00 and the form Id currently there to trigger the flow `apZrpKcK78xzrPcAfRrfac`: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg

### adaptors
mssql AND postgresql

## Expected behavior
DB column that are currently of `text` text support `unicode` characters.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @lakhassane When I turn on 'execute: true' settings and run this job `02a` to auto-execute the sql script in Postgres, it fails with the error `error: type "nvarchar" does not exist`.
https://www.openfn.org/projects/p5x4g4/runs/rmk79jyp

See here for the triggering run for job `00`: https://www.openfn.org/projects/p5x4g4/runs/r9w9gpy9
Feel free to clear state & re-run this job on prod: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg

**Comment by aleksa-krolls** [comment]
@lakhassane is this issue resolved? can we close?

**Comment by lakhassane** [comment]
@aleksa-krolls I just saw this issue. I don't think it was assigned yet. I will ask Taylor

**Comment by aleksa-krolls** [comment]
Ok thanks @lakhassane... it might be resolved if we're now getting green checks on job `02a` and able to execute sql in postgres.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , the [run you've added above](https://www.openfn.org/projects/p5x4g4/runs/rmk79jyp) is for the postgres job, not the mssql job. As far as I can tell this issue is closed, but that failing run on the postgres job might be evidence of a new issue.

@lakhassane , while this is probably (confusingly) _unrelated_ to the `text` to `nvarchar` conversion that was required in _this_ issue, do you know why that run above (using `language-postgresql`) might have attempted to insert a column with type `nvarchar`?

**Comment by lakhassane** [comment]
I think I got it @taylordowns2000 
We had `nvarchar` in `processForm` which then would try to insert that datatype to `postgresql` but nvarchar exists only in `mssql`.

What we should note here is that whatever datatype you used in `processForm` should be something that is VALID in postgresql (because it is the default). 

If you want the equivalent in mssql, you shoul go in `syncToMssql` and make the conversion.

So yes @aleksa-krolls this can be considered done.

**Comment by taylordowns2000** [comment]
to be clear, what @lakhassane suggests here "If you want the equivalent in mssql, you shoul go in syncToMssql and make the conversion." has already been done in https://github.com/OpenFn/ConSoSci/commit/383037060e4c96e10f2fa594baffd659e77f2d25 and https://github.com/OpenFn/ConSoSci/commit/a80d8decbc6025eda9e72f7b7ad30af63c62ccca .

there was an unrelated issue with #125 causing the behaviour on this postgres job which has now been resolved. closing

**Comment by aleksa-krolls** [comment]
@lakhassane WCS shared that for mssql, we should use `nvarchar` instead of `varchar`. 

https://github.com/OpenFn/ConSoSci/blob/master/automation/02c-syncToMssql.js

**Comment by lakhassane** [comment]
replacement made for `varchar` and `text` to use `nvarchar` in `mssql`
