### ISSUE TITLE
Auto sql script error: `EndDate` duplicated but column names in each table must be unique

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#137]
## Describe the bug
@dianedetoeuf ran the automation solution for this SocioEcoDB form `aukhdejQU76K33caCkF4rP`

Job `02c-syncToMssql.js` throws the error...
https://www.openfn.org/projects/p5x4g4/runs/r7xb4jjz
```
RequestError: Column names in each table must be unique. Column name 'EndDate' in table 'WCSPROGRAMS__SocioEcoDB' is specified more than once.
```

## To Reproduce
Re-run job 00 using this form info: https://www.openfn.org/projects/p5x4g4/runs/raaxnyyr

### adaptor 
mssql 

### expression.js
https://github.com/OpenFn/ConSoSci/blob/master/automation/02c-syncToMssql.js

### state.json
See LP for wcs test mssql

**Comment by taylordowns2000** [comment]
@aleksa-krolls , @dianedetoeuf , previously we decided to convert any question called `end` to `end_date` because we are not allowed to create columns in the DB called `end`—it's a "reserved word".

Line 76 of `automation/01-processForm.js` does this conversion:
```js
      if (obj.name == 'end') {
        obj.name = 'end_date';
      }
```
If a form (like `aukhdejQU76K33caCkF4rP`) has two different questions: `end` and `end_date`, then we'll end up with two different `end_date` columns and the run will fail as above.

**Quick question for resolution:** what would you like us to call the renamed `end` field so that it doesn't conflict with other questions in Kobo forms?

My recommendation is that we convert kobo questions called `end` to DB columns called `end__safe`, making use of the double-underscore (`__`) to _reduce the probability_ of collisions with other Kobo questions. Note that this will mean any auto-generated tables that used the old solution will have `end` questions stored as `end_date` and anything using this solution after today will have `end` questions stored as `end__safe`.

**Comment by aleksa-krolls** [comment]
Thanks @taylordowns2000. Maybe if we see `end`, we configure this as a column called `form__end_date` (making use of the double underscores). @dianedetoeuf do you have a preference for what this column name should be for the Kobo standard question `end`?

**Comment by taylordowns2000** [comment]
Happy to go with whatever @dianedetoeuf decides! Just let me know and I'll implement.

My two cents on naming: I might actually go with `form_date__end` instead of `form__end_date`... the idea being that we'd want to use the `__` to denote separation between what the question is actually called (`end`) and _the stuff that we're arbitrarily writing_ to keep it from being rejected by the DB. So something prettier, but aligned in spirit with:
```
<TAG INDICATING TECHNICAL CHANGE>__<QUESTION NAME>
```
is preferable in my mind to

```
<TAG INDICATING TECHNICAL CHANGE>__<QUESTION NAME>_<ANOTHER CHANGE>
```

**Comment by dianedetoeuf** [comment]
Hi, alright, then form_date__end seems like a good option to avoir future conflicts. Lets fo with that, and I'll inform Steve about the change. 
Thank you so much!
