### ISSUE TITLE
Auto-generated job fails to sync data even when `setNull` option is specified

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#138]
## Describe the bug
See run failure with error `Error converting data type varchar to numeric`: https://www.openfn.org/projects/p5x4g4/runs/r9wn4e6k

I thought this was resolved with #134 ... but even when I think this `setNull` option is specified and the adaptor version looks updated, the job still fails. 

## To Reproduce
1. You can run the auto-generated job ( https://www.openfn.org/projects/p5x4g4/jobs/jvr58e ) against this Message state: https://www.openfn.org/projects/p5x4g4/messages/mj484awr
2. This is the run with the formId that auto-generated the job: https://www.openfn.org/projects/p5x4g4/runs/r7xjady4

### expression.js
https://www.openfn.org/projects/p5x4g4/jobs/jvr58e

### state.json
See LP: `wcs test mssql db`
https://www.openfn.org/projects/p5x4g4/messages/mj484awr

**Comment by aleksa-krolls** [comment]
@lakhassane We're testing the automation solution with some new Kobo forms and encountered this issue. Please let @daissatou2 know when ready to test again and she can re-run the flow from the beginning starting with the `A1` job.

**Comment by lakhassane** [comment]
Few feedbacks on this one @aleksa-krolls:
1. The job to check now has change since we made updates on how we named tables. Here is the new one: https://www.openfn.org/projects/p5x4g4/jobs/jvgkze (`WCSPROGRAMS_SocioEcoDB` instead of `WCSPROGRAMS__SocioEcoDB` 

2. the error was due to value we had for the column `__version__`. In the form definition the type is `calculate`. From previous specs `calculate` was turned to `decimal` for `mssql`. However, the value from the submission was a string thus the failure.
Changing calculate to text in `processForm` would correct the issue (I don't know what could be the future value of calculate fields though).

Let me know if good to go with that.

**Comment by aleksa-krolls** [comment]
@lakhassane Feedback here...
1. thank you... will test now that the DB tables are being names properly. 
2. We're learning that `calculate` fields are typically `numbers`, but they might sometimes be `text` or `date` values. Therefore would you recommend that the default column type should be varchar or whatever mssql data type we use to capture text values?

**Comment by lakhassane** [comment]
yess @aleksa-krolls changing to `varchar` or `text` should be good

**Comment by aleksa-krolls** [comment]
Great @lakhassane ... please go ahead and use varchar or nvarchar (or whatever in mssql supports unicode). 

Let me and @daissatou2 know whenever ready to test.

**Comment by lakhassane** [comment]
@aleksa-krolls I made the change
