### ISSUE TITLE
New issues in Arcadia job

### ISSUE THREAD

**Issue by dianedetoeuf** [OpenFn/ConSoSci#172]
## Describe the bug
The job fails because of Invalid column name 'DatasetUuidId'. The column name is the same in the DB so not sure what to do.

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/wcs/runs/061b0bd2-21fd-765e-a841-e35e2479682c

### expression.js
Link to the job itself in Github: (https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js)

## state
See LP for `WCS Programs DB`
https://www.openfn.org/projects/wcs/messages/061b01fb-dd8c-7d11-917c-0d89c03ff7df

## adaptor
mssql

**Comment by aleksa-krolls** [comment]
@dianedetoeuf Confirming you've checked that there's a column `DatasetUuidId` (spelled exactly like this) on the table `WCSPROGRAMS_ProjectAnnualDataPlanDataSetSurveyType`?

**Comment by aleksa-krolls** [comment]
Also @dianedetoeuf ... @lakhassane suggested checking that there is unique constraint configured for that column since you are using this as the upsert key

**Comment by dianedetoeuf** [comment]
Yes we've checked the spelling, and ok will look at unique constraint.

**Comment by dianedetoeuf** [comment]
We have unique constraint but the job still fails for the same reason.

**Comment by aleksa-krolls** [comment]
@lakhassane can you please check this out whenever you have the chance? Check out the comments above.

**Comment by dianedetoeuf** [comment]
Hi, any news on this?

**Comment by lakhassane** [comment]
@aleksa-krolls @dianedetoeuf we have moved forward with another valid error: https://www.openfn.org/projects/wcs/runs/061b8c4f-0142-75a5-8825-d475f382c241

Looks like the mapping has a column that does not exis in the DB (`WCSPROGRAMS_DataSetSurveyTypeName` - check `L79`)

**Comment by dianedetoeuf** [comment]
okay, I've fixed the column names. Would you be able to help on this new error: https://www.openfn.org/projects/wcs/runs/061b8e93-8ea6-754b-9d7f-f1c5a8924015 ?

**Comment by lakhassane** [comment]
Hey @dianedetoeuf I see you use `DatasetUuidId` in here https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js#L60

`DatasetUuidId` is not a variable in the state. Did you mean to use `body._id`?

I made that correction. Feel free to replace it if it should be something else.

For more context check here https://github.com/OpenFn/language-mssql#find-a-single-value-for-a-table: the `where` object in the `findValue` expect a value from state as a second argument

**Comment by aleksa-krolls** [comment]
@dianedetoeuf Looks like the error is now something with lookup values not found: https://www.openfn.org/projects/wcs/runs/061b9c2a-14f6-7a98-a473-71b157bd374e
```
RequestError: Cannot insert the value NULL into column 'WCSPROGRAMS_ProjectAnnualDataPlanID', table 'wcsprograms.dbo.WCSPROGRAMS_ProjectAnnualDataPlanDataSetSurveyType'; column does not allow nulls. UPDATE fails.
```
Keep us posted if/how we can help.

**Comment by dianedetoeuf** [comment]
Thanks, yes using body id seems logical. But I don't know why its not finding the lookup values. 

ProjectAnnualDataPlanDataSetSurveyType is a many to many table where we're identifying the dataset and the types of surveys that dataset will be using. It contains the values ProjectAnnualDataPlanID and DataSetSurveyTypeID. 

What we want is to get those IDs using a lookup function on the tables ProjectAnnualDataPlan and DataSetSurveyType using their respective ExtCode fields for the lookup.

For ProjectAnnualDataPlan, the ext code should be the id of that survey. It's not null as it's defined from the beginning, in section 1 of the mapping. So I don't understand why the run says it's null...

**Comment by aleksa-krolls** [comment]
Hey @dianedetoeuf when we upsert rows into the tables `WCSPROGRAMS_ProjectAnnualDataPlan`, it does NOT look like we're mapping to the column `WCSPROGRAMS_ProjectAnnualDataPlanExtCode`. Therefore, I bet this column is blank on your `WCSPROGRAMS_ProjectAnnualDataPlan` records... which is why this job cannot find a matching record. 
https://github.com/OpenFn/ConSoSci/blob/ca701e1205ebb90078871e2459b358e02e1e598d/arcadia/arcadiaSiteDataCollection.js#L11-L36

If I review the operation above, it _does_ look like we have mappings for `AnswerId` and `DatasetUuidId`... so maybe you can use these instead of the `ExtCode` column as lookup keys? If yes, then you change the mapping on L54 as follows: 
```
WCSPROGRAMS_ProjectAnnualDataPlanID: await findValue({
          relation: 'WCSPROGRAMS_ProjectAnnualDataPlan',
          uuid: 'WCSPROGRAMS_ProjectAnnualDataPlanID',
          where: { AnswerId : body._id },
        })(state),
```
Do you want to pick which column on table `WCSPROGRAMS_ProjectAnnualDataPlanID` to use as the new lookup key in the `where` clause and then try re-running the message?

**Comment by dianedetoeuf** [comment]
okay cool, I've used Answer ID and it seems to fix it.

New error though: TypeError [Error]: Cannot read property '0' of undefined on 
https://www.openfn.org/projects/wcs/runs/061ba014-367c-7539-9487-1eaa79509233

**Comment by aleksa-krolls** [comment]
@dianedetoeuf It looks like this mapping below is returning null values...
https://github.com/OpenFn/ConSoSci/blob/6df5e78401d69ab1f602b37036b807c73d8c32ca/arcadia/arcadiaSiteDataCollection.js#L130-L134

Can you confirm there records in the table `WCSPROGRAMS_CameraTrapSetting` with `ExtCodes` that match these values we see provided in the Message state? 
```
"group_qp5by62/Which_of_the_followi_ata_you_will_collect": "still_images_will_be_collected video_images_will_be_collected",
```

**Comment by dianedetoeuf** [comment]
@wcs-sgallo could you help here?

**Comment by wcs-sgallo** [comment]
The values for WCSPROGRAMS_CameraTrapSettingExtCode were:
still_images
video_images
connected

I've added _to_be_collected to these.

**Comment by aleksa-krolls** [comment]
@wcs-sgallo it looks like these Kobo values end with `_will_be_collected`, not `_to_be_collected`. Can you update the ExtCodes in the DB? Or do we need to re-label the Kobo values?

**Comment by wcs-sgallo** [comment]
Updated.

**Comment by aleksa-krolls** [comment]
@wcs-sgallo @dianedetoeuf there are some mappings that need to be reviewed for `WCSPROGRAMS_ProjectAnnualDataPlanDataSet`....
1. [L276-283](https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js#L276-L283) is throwing this error... is this the right column name?: https://www.openfn.org/projects/wcs/runs/061bb5a0-ccc8-70c6-af0d-f56523fa7f55
2. [L288](https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js#L288-L289) will probably need a `findValue` mapping if this `WCSPROGRAMS_DataAccessFrequencyID` is a FK column that looks up to a reference table

**Comment by dianedetoeuf** [comment]
I'm trying to replace NULLS by NA here also but doesn't work either. See https://www.openfn.org/projects/wcs/runs/061bb6b7-b100-7b20-88ec-4852e653ccde

**Comment by dianedetoeuf** [comment]
Hi, we've made the column nullable to move forward. I have a new error that i don't know how to fix: https://www.openfn.org/projects/wcs/runs/061bb707-3fb0-7961-a65f-74a4810da899

**Comment by aleksa-krolls** [comment]
@elias-ba Can you help out with the latest error today or Monday? 
See run failure: https://www.openfn.org/projects/wcs/runs/061bcaa5-7871-7a1c-a652-a338e491f84c
```
The MERGE statement conflicted with the FOREIGN KEY constraint "FK_WCSPROGRAMS_ProjectAnnualDataPlanDataSetDataTool_WCSPROGRAMS_DataToolID". The conflict occurred in database "wcsprograms", table "dbo.WCSPROGRAMS_DataTool", column 'WCSPROGRAMS_DataToolID'.
```
I _think_ the error is because there are 2 `paper` values in state (`"datasets/data_collection_tool": "paper"` - see L104 and 51 in [the Message](https://www.openfn.org/projects/wcs/messages/061b9aea-c05c-7061-81e5-dd6430e4fb67)), so we're trying to upsert 2 of the same rows into the DB table `WCSPROGRAMS_ProjectAnnualDataPlanDataSetDataTool` ([see job lines](https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js#L359-L384)) that both have the mapping below...
```
WCSPROGRAMS_DataToolID: await findValue({
              relation: 'WCSPROGRAMS_DataTool',
              uuid: 'WCSPROGRAMS_DataToolID',
              where: { WCSPROGRAMS_DataToolExtCode: 'paper' },
            })(state),
```
If that's the case, should we maybe add logic to de-duplicate `dataCollectionTools` before insert to ensure that we would only insert 1 row for the value `paper`? 
https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js#L345-L347

Fyi, I think we did this before in a different WCS job: https://github.com/OpenFn/ConSoSci/blob/master/vegetation/VegetationClassficationAndTreeMeasurementForm.js#L575-L581

**Comment by elias-ba** [comment]
@aleksa-krolls I think this is more than having 2 paper values in state. I have explicitly removed one of the paper values and we're still having the error. I think this is related to some foreign keys constraints in the DB that we need to know to be able to propose a solution. This does not exclude your intuition on the origin of the error but I think that the solution can only come from a good knowledge of the constraints which prevents the request from passing and to see if it is something that the we can settle on our side.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 
To successfully process the Merge error for [this state](https://www.openfn.org/projects/wcs/messages/061b9aea-c05c-7061-81e5-dd6430e4fb67)... we need to transform the value `paper` in state.data --> `paper_form` to find the correct `WCSPROGRAMS_DataTool` record. 
This transformation needs to be applied to 3 source values: 
- `datasets/data_collection_tool` : [see L347](https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js#L346-L347)
- `datasets/data_management_tool`: [see L397](https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js#L397-L399)
- `datasets/data_analysis_tool`: [see L443](https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js#L443-L445)

**Comment by taylordowns2000** [comment]
@aleksa-krolls i've added another necessary cleaning rule [here](https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js#L8)

but there are still at least two things that will continue to fail. do you know what [`state.dataChallengeMap`](https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js#L540) and [`state.dataAssistanceMap`](https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js#L581) should be? they're not defined, and will always blow up.

In a similar vein, in order to get `data_management_tool` and `data_analysis_tool` to work I had to ditch the reference to some non-existent "maps" in state and instead implement `findValue`. should i do the same here? see my changes to fix the first two non-existent maps:
- [removing "dataToolsMap" on line 424](https://github.com/OpenFn/ConSoSci/commit/8efe295a0e0079b4dc6170c8316fe4ce90a8785d#diff-d2446aa6dd701ffa156381970f9c146f7945fdf684383292d524ed6a899f672fL424)
- [removing "dataToolsMap" on line 470](https://github.com/OpenFn/ConSoSci/commit/8efe295a0e0079b4dc6170c8316fe4ce90a8785d#diff-d2446aa6dd701ffa156381970f9c146f7945fdf684383292d524ed6a899f672fL470)

**Comment by aleksa-krolls** [comment]
thanks for the help @taylordowns2000 ... fyi, turns out even more values in the reference tables were missing or mismatched what we received from Kobo, but I was able to resolve. Everything has now been reprocessed successfully.

**Comment by elias-ba** [comment]
Thanks a lot @aleksa-krolls for the information. I was interested in knowing the root of that error.

**Comment by aleksa-krolls** [comment]
@lakhassane The original error `Invalid column name 'DatasetUuidId'`first reported in this issue has surfaced again after @dianedetoeuf implemented a new set of mappings: https://github.com/OpenFn/ConSoSci/blob/master/arcadia/arcadiaSiteDataCollection.js#L623-L670

However, she has confirmed that the column `DatasetUuidId` is present on the target table. 

## Request
Can you please review the error and prior commits on this issue to see if you can resolve it? 
If you have any questions or would like to discuss with Diane, please coordinate with her to schedule a call for later this week to talk through it and consider a co-coding session. 

## To replicate 
See run failure and feel free to re-run on platform: https://www.openfn.org/projects/wcs/runs/061dd8e1-8fb1-78d7-a8b8-749bba02eac4

## state
See LP for `WCS Programs Database`
https://www.openfn.org/projects/wcs/messages/061dbf5a-393a-7ad0-8610-7aa87a6fc0f7

Keep me posted if any immediate questions!

**Comment by lakhassane** [comment]
@aleksa-krolls  here is the culprit: `DataSetUUIDId`.
In the mapping, that column was written as `DatasetUuidId` while it was recorded as `DataSetUUIDId` in the table. mssql being case sensitive it will return an error because that exact column, `DatasetUuidId`, does not exist in the table.

I corrected that (`L646` and `L663`). Find here the latest run that shows another error with `AnswerId` https://www.openfn.org/projects/wcs/runs/061dde65-0bd3-74bd-88f6-cb2089fa04a4

**Comment by aleksa-burn** [comment]
@dianedetoeuf check out Mamadou's comment above. Is `AnswerId` in the DB? And is the capitalization correct? 

If you're still not sure what's wrong, let us know what times you available today and tomorrow, and @lakhassane can plan to jump on a call with you to work through this.

**Comment by aleksa-krolls** [comment]
@dianedetoeuf check out Mamadou's comment above. Is AnswerId in the DB? And is the capitalization correct?

If you're still not sure what's wrong, let us know what times you available today and tomorrow, and @lakhassane can plan to jump on a call with you to work through this.

**Comment by dianedetoeuf** [comment]
Hi, we've added AnswerID and now have a new error  "Cannot update identity column 'WCSPROGRAMS_ProjectAnnualDataPlanDataSetDataSetOpenAccessChallengeID'."

**Comment by dianedetoeuf** [comment]
Actually found the issue, that column had a much shorter name :) We have green check now!
Thanks for all your support again!
