### ISSUE TITLE
Tables not syncing in Sharks & Rays

### ISSUE THREAD

**Issue by dianedetoeuf** [OpenFn/ConSoSci#176]
## Issue 
A few tables related to Sharks & Rays are not being synced: 
- WCSPROGRAMS_SharksRaysSales
- WCSPROGRAMS_SharksRaysSample
- WCSPROGRAMS_SharksRaysFishCatch
- WCSPROGRAMS_SharksRaysCatchDetails
- WCSPROGRAMS_SharksRaysBoat
- WCSPROGRAMS_CatchDetailsGear

One of the forms had been modified and I updated the job to take the different versions into account. After reprocessing the messages, the job is successful but the tables remain empty.

There seem to be a few "skipping upsert" for some reason at the end... Maybe this is the cause?
See example run: https://www.openfn.org/projects/wcs/runs/061f7f98-0a05-72db-826d-190a57f0dab8

## expression
Job here: https://github.com/OpenFn/ConSoSci/blob/master/sharks_rays/autoSharksRays.js

## state
See LP for `WCS Programs Database`

Ideally the job needs to handle both new and old versions of state: 
1. State example with _new_ version: https://www.openfn.org/projects/wcs/messages/061f7f98-0143-7817-b8ce-51e4299d6f96
2. State with old form version: https://www.openfn.org/projects/wcs/messages/0611b5f1-f000-7de6-ad7e-033bfba9bf63

## adaptor 
mssql

**Comment by aleksa-krolls** [comment]
@lakhassane when you have time, please check out this issue Diane flagged. Because it's a new form version, I'm wondering if the mappings currently in place don't support the data structure. Once you've figured out what's going on here, I'd be happy to review with you and discuss next steps... ideally we need it working for both states linked to above.

**Comment by aleksa-krolls** [comment]
@daissatou2 we noticed you've made multiple changes over the last couple of days. Was there a specific day/time that this _stopped_ working? Or has it never been working since you made the changes? 

@lakhassane here some additional Messages you can test against: 
1. With `"boat/catch_details"` array: 
https://www.openfn.org/projects/wcs/messages/061f25f1-6f3e-71bf-b07a-675e74dcb349
2. With `"boat/catch/catch_details"` array: 
https://www.openfn.org/projects/wcs/messages/061f25f1-6f33-7a5b-b4c6-dca09db200be

**Comment by dianedetoeuf** [comment]
Those tables were never synced at all, so I guess from the beginning... But they are "sub" table so we didn't really notice it before trying to do the dashboards. What is weird is that no data is being added at all, even the data from the standard form. I did 2 types of changes: 
- For the mapping of those sub tables, I thought because everything was called "Mapping" the job was confused and didn't know what to map. So I gave more specific names to the mapping of each sub-tables (Example mappingVendor, mappingDetails...etc). I've added a comment to say where I've added it. Not sure if that was useful or not :)
- Then for the fields that have a new version, added the "or" with the alternative mapping.

**Comment by aleksa-krolls** [comment]
@dianedetoeuf We need to discuss how to handle the different form versions, because Mamadou and I are seeing that the different forms have _very_ different data structures. I will be hard to have 1 job work for all. 

For example, here is what some of the state looked like in the original form used when first writing the job... [see message](https://www.openfn.org/projects/wcs/messages/0611b5c4-e000-7c35-b26e-d9c30ee1c44c) that contains nested arrays... `boat/catch_details` under `boat`.  
```
"boat": [
      {
        "boat/boat_info": "no",
        "boat/catch_details": [
          {
            "boat/catch_details/dna_sample_collected": "no",
            "boat/catch_details/fork_length": "35.0",
            "boat/catch_details/gear_type": "spear_gun",
            "boat/catch_details/species": "unknown_species",
            "boat/catch_details/total_length": "42.0",
            "boat/catch_details/type": "shark"
          }
        ]
      }
    ],
    ```
 But then in more recent form versions, we don't see the `boat` array - see [this message](https://www.openfn.org/projects/wcs/messages/0611b5c4-e000-7c35-b26e-d9c30ee1c44c) with `boat/catch/catch_details` and [this message](https://www.openfn.org/projects/wcs/messages/061f25f1-6f3e-71bf-b07a-675e74dcb349) with just `boat/catch_details`. 
    ```
    "boat/catch/catch_details": [
      {
        "boat/catch/catch_details/comment": "Not in a pile",
        "boat/catch/catch_details/disc_length": "80.0",
        "boat/catch/catch_details/disc_width": "154.0",
        "boat/catch/catch_details/gear_type": "drift_net",
        "boat/catch/catch_details/genus": "unknown_ray"
     }]
   ````

**Comment by dianedetoeuf** [comment]
Hi, 

Yes they’ve added 2 groups, so we have either boat/catch_details/question or boat/catch/catch_details/question; and either market_details/vendor/sales/question or market_details/market_001/vendor/sales/question.

I've added the alternatives to all the questions that are impacted. Lets talk about it at our sync today!

**Comment by aleksa-krolls** [comment]
@lakhassane got some feedback from @dianedetoeuf. There are 2 things going on here...

1. The job still doesn't work for the original form version it was created for. See [this Message](https://www.openfn.org/projects/wcs/messages/0611b5c4-e000-7c35-b26e-d9c30ee1c44c) with a `boat[*}` array and [related run](https://www.openfn.org/projects/wcs/runs/061f7f2a-9a29-72d7-b861-4821d4fdf61f) that shows no `boat` or catch details are inserted... only the `WCSPROGRAMS_SharksRays` table was upserted. 
Can you please get this job working for this version of `state.data`. 

2. Once that is fixed, we will make another job to handle the other form versions that do _not_ have the `boat[*]` array. I will follow up with a separate issue for that, if your support is needed. Diane is working on determining which forms belong to this new version and how the mappings might change. 

How does that sound for next steps? Keep me posted if you want to briefly chat.

**Comment by lakhassane** [comment]
@aleksa-krolls I updated the job according to the state to make it work.
What to learn for future reference is that when you have a job with multiple `each`, you cannot use `each(dataPath('ARRAY[*]'), ...)`
as each will overwrite `state.data`. Then `dataPath` won't be able to find the array to iterate on.

I plucked out the different arrays to put them directly into state (that stays unaltered) and we can use `each('$.body.ARRAY[*]')`.

One last thing to check for @dianedetoeuf is the existance of unique constraints on the table for the upsert. The job is still using `GeneratedUuid`for upsert but that column does not exist on the db. Could you please check which column from the database should be used for each table and if that column has a unique constraint set?

**Comment by aleksa-krolls** [comment]
thanks @lakhassane. And noted re: `each(...)`. I'll ask you to walk me through it again tomorrow so that I can share back with WCS on our next call. 

@dianedetoeuf I need to test Mamadou's changes, but this means that the job fix for the original form version might be near-complete, pending your confirmation on whether `GeneratedUuid` is a column on these tables with a uniqueness constraint configured: 
WCSPROGRAMS_SharksRaysSales
WCSPROGRAMS_SharksRaysSample
WCSPROGRAMS_SharksRaysFishCatch
WCSPROGRAMS_SharksRaysCatchDetails
WCSPROGRAMS_SharksRaysBoat
WCSPROGRAMS_CatchDetailsGear

FYI, Mamadou's next step will be to start on the V2 job for the modified form version. Keep you posted.

**Comment by dianedetoeuf** [comment]
Hi, the issue with GeneratedUuid seems to be a regular one, which is strange because we are using the tables provided by the script generated by the automation job.
It should be there now.

**Comment by lakhassane** [comment]
@dianedetoeuf thanks for the feedback. We are almost there.
We are not mapping some of the table but we still have a column issue with `WCSPROGRAMS_CatchDetailsGear` and `WCSPROGRAMS_SalesGear`. Those tables don't have `GeneratedUuid` do you know what column should be used to upsert on? Also can you add the uniqueness constraint for that column in the db?

Also I think those 2 are lookup tables so instead of `GeneratedUuid`, the constraint should be on 2 fields just as we did with TT jobs where we had this as uuid `['TT_SiteRegistrationID', 'TT_AnimalID']`.

**Comment by aleksa-krolls** [comment]
It looks like `WCSPROGRAMS_SalesGear` and `WCSPROGRAMS_CatchDetailsGear` are m:m tables that have foreign key fields mapped to other lookup tables. 

So I've added a unique column `GeneratedUuidId` to each. @lakhassane I'm not encountering a TypeError when trying to run: https://www.openfn.org/projects/wcs/runs/061fd218-2d9d-76b4-8606-01129b3cb82e

**Comment by lakhassane** [comment]
@aleksa-krolls a `return` was missing (check run now https://www.openfn.org/projects/wcs/runs/061fd27a-99a6-70d7-be87-d027ca0ff102).
However, the message you used does not have a `boat` array. Using [this message](https://www.openfn.org/projects/wcs/messages/0611b5c4-e000-7c35-b26e-d9c30ee1c44c) with a boat array works fine now => https://www.openfn.org/projects/wcs/runs/061fd2af-529b-70a8-b113-924615a7c5ad

**Comment by aleksa-krolls** [comment]
@lakhassane Got it... findValues implemented: https://github.com/OpenFn/ConSoSci/commit/727362f397d5a900c8d85112be931553e99512a7#diff-188808a0ad2b2af65908961290d008b6c80e3278f917a3b3cfe777214274d100

But see L244 of [this run](https://www.openfn.org/projects/wcs/runs/061fd2f3-d623-795f-8028-1af9a729607e)... why is `WCSPROGRAMS_GearID: undefined`? I see `spear_type` in the DB, so that findValue should return a value. 
<img width="534" alt="Screen Shot 2022-02-04 at 3 51 15 PM" src="https://user-images.githubusercontent.com/16758106/152540400-b17cd599-da92-44a2-ac29-2baeeda2707a.png">

**Comment by lakhassane** [comment]
I corrected that final issue @aleksa-krolls. It's all set: https://www.openfn.org/projects/wcs/runs/061fd413-1785-74e4-8c4d-7d5131e0a47c

I will replicate those changes to the job for the new versions of state

**Comment by aleksa-krolls** [comment]
Awesome, thanks @lakhassane ! Keep me posted when that new job is ready also for testing. 

@dianedetoeuf can you please check out the output of this run in DB to confirm it is now syncing as you'd expect? https://www.openfn.org/projects/wcs/runs/061fd413-1785-74e4-8c4d-7d5131e0a47c

On Monday, I'll test Mamadou's form v2 job changes, and then start work on getting the forms re-processed by the appropriate job.

**Comment by dianedetoeuf** [comment]
Hi, we still have some fields that are returning NULLs, for example AnswerID, Genus, TypeID and Sex in the CatchDetails. And still no data in Vendor and Gear. I've asked Steve to send me a list of all fields being filled for 2 specific IDs (one with landing site info, the other with market info), so we can look in details at what's missing.

**Comment by dianedetoeuf** [comment]
Also, the species are not found in the Taxa table because the ExtCode field is used for something else and because of the underscore in the species name. Can we use ScientificName instead, and replace the _ by a space?

**Comment by aleksa-krolls** [comment]
@dianedetoeuf re: `ScientificName` - we can make this change, but it looks like this column is blank in the DB for all values? Will you/Steve be uploading data here? 

@lakhassane It's sounding like here are the 3 changes/issues to focus on for job v1 (I will post on the job v2 issue with relevant changes: 
1. Replacing `_` with a space ` ` in every kobo dataValue mapped to `ScientificName`. For example in [this state](https://www.openfn.org/projects/wcs/messages/0611b5c4-e000-7c35-b26e-d9c30ee1c44c), convert `unknown species` --> `unknown species`

2. No data is being uploaded to table `WCSPROGRAMS_SharksRaysCatchDetails`. Does the job correctly handle for the nested array `boat/catch_details[*]` which is nested under `boat[*]`? See example state: https://www.openfn.org/projects/wcs/messages/0611b5c4-e000-7c35-b26e-d9c30ee1c44c

3. Can you please look into why `WCSPROGRAMS_SharksRaysVendor` and `WCSPROGRAMS_SalesGear` may not be uploading correctly? Here is a sample state for job v1: https://www.openfn.org/projects/wcs/messages/061d9d13-41b6-7342-918b-b0e7babd9da7

**Comment by aleksa-krolls** [comment]
@dianedetoeuf fyi, we've been going back and forth for much of the day are down to the last couple of issues. 

@lakhassane Here out the 2 outstanding issues I'm seeing after further testing that I need your help to resolve. 
1. `WCSPROGRAMS_SharksRaysCatchDetails.WCSPROGRAMS_TaxaID_Species` is null, even though a `WCSPROGRAMS_Taxa` record was added where `ScientificName = ‘unknown species’`. Why is this mapping not working? https://github.com/OpenFn/ConSoSci/blob/master/sharks_rays/autoSharksRays.js#L332-L336

2. I made the changes so that records should insert correctly into the `Sales` table, but now I'm encountering the below error for [this message](https://www.openfn.org/projects/wcs/messages/061d9d13-41b6-7342-918b-b0e7babd9da7). Lmk if we need to jump on the phone to discuss this one tomorrow. 
`RequestError: Timeout: Request failed to complete in 15000ms` 
https://www.openfn.org/projects/wcs/runs/06203f7e-20ed-7949-8a66-ecff67273241

**Comment by aleksa-krolls** [comment]
@lakhassane Your latest changes are working, and some messages are now successfully syncing. But see below for the latest failure I'm encountering: https://www.openfn.org/projects/wcs/runs/06204b0f-edc7-7e63-b265-0dfafa9ff1a1
```
Violation of UNIQUE KEY constraint 'WCSPROGRAMS_CatchDetailsGear_UN'. Cannot insert duplicate key in object 'dbo.WCSPROGRAMS_CatchDetailsGear'. The duplicate key value is (<NULL>).
```
This issue sounds similar to the `SalesGear` problem we encountered yesterday.

**Comment by aleksa-krolls** [comment]
fyi @dianedetoeuf it looks like the original form version is syncing well now from the handful of tests I've done. I'm going to bulk re-process these, and then review the DB to see if things are looking good... tomorrow I'll invite you to do the same. 
Re: the modified form version, Mamadou is making the last bug fixes there... so we should also be able to reprocess these tomorrow :)

**Comment by dianedetoeuf** [comment]
great, thank you for the updates!

**Comment by aleksa-krolls** [comment]
@dianedetoeuf and team are reporting that no records are being inserted to the table `WCSPROGRAMS_SharksRaysSample`. I'm looking in Kobo and not finding many submissions with this data, but there are a couple at least. 

@lakhassane @grayey  can you two please look at why the mappings for this `WCSPROGRAMS_SharksRaysSample` table are not working?
1. Here is a sample state: https://www.openfn.org/projects/wcs/messages/061afa31-2cc5-79ce-8128-87e2daa49fa6
2. Here is the job mapping that might not be working: https://github.com/OpenFn/ConSoSci/blob/master/sharks_rays/autoSharksRays.js#L501-L538

If we make any changes for job V1, let's please replicate in job V2.

**Comment by lakhassane** [comment]
@aleksa-krolls correction done. We didn't have a state with fish_catch yet so I did not know what path should be used.

**Comment by aleksa-krolls** [comment]
@lakhassane can you please replicate these changes in V2 job? (if you haven't already)
Let's assume the path is the same in V2, and I'll work on finding data to test & validate this. Thanks!

**Comment by lakhassane** [comment]
Yes @aleksa-krolls. It's replicated also
