### ISSUE TITLE
Introduce MSSQL compatibility for the `automation` solution

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/ConSoSci#75]
Currently the `automation` solution executes sql in Postgres and write OpenFn jobs leveraging `language-postgres`. 

If WCS wanted the same solution, but with an option to integrate with `mssql`, what would be... 
1. Estimated level of effort introducing this compatibility (est. # of days & consider Engineer team time for testing)
2. Considerations for ongoing maintenance? Would we replicate ALL jobs in the `automation` solution, or only jobs `02a` and `02b`? 

I want to share a budget estimate with WCS tomorrow afternoon. Let me know if helpful to discuss tomorrow.

**Comment by taylordowns2000** [comment]
1. We have the same _data_ operations in `language-mssql` and we have in `language-postgres`.
2. Because of (1), `02b` will likely not change.
3. We will need to write _metadata_ operations for `language-mssql`: `insertTable`, `modifyTable`, `describeTable`.
4. If we can create the operations in (3) with the same contract as  `02a`, which `creates` or `alters` postgres tables, we won't need to change `02a` at all.

@lakhassane and I think (3) will take half a day and if all goes _well_ (4), then nothing else will be needed and WCS could choose to run job `02a` using _either_ the postgres adaptor or the mssql adaptor. It would be interchangable. If we can't achieve (4), then we'll need another hour or so to make small modifications—effectively creating `02a-forPostgres` and `02a-forMssql`.

I've renamed this issue and provided the estimate here.

**Comment by aleksa-krolls** [comment]
Estimate shared with the client, closing for now.

**Comment by aleksa-krolls** [comment]
@lakhassane Not all the helper functions included in our auto-generated job (like `upsertIf(...)` are in the mssql adaptor). So I've created a related issue: 

Fyi, see these runs for how I've run on prod: https://www.openfn.org/projects/p5x4g4/runs?endDate=2021-06-09T15%3A32%3A35.471Z&searchString=AUTO&startDate=2021-06-09T15%3A26%3A35.491Z&success=0

When the mssql adaptor changes are done, please clear state and re-run the automation flow. Job 1 should fetch this from Kobo..
```
{ uid: 'apZrpKcK78xzrPcAfRrfac', p1:'WCSPROGRAMS', p2: 'SharksRays', tableId: 'SharksRays'},
```

THEN run the auto-generated OpenFn job against this state: https://www.openfn.org/projects/p5x4g4/messages/mbp3nq4p

Let me know when this^ data is successfully sending to the DB and then I will re-test. **Please use the creds `WCS Test Mssql DB`**

**Comment by lakhassane** [comment]
@aleksa-krolls I re-run the whol flow to test and here is the output for the job generation and DB generation.
https://www.openfn.org/projects/p5x4g4/runs?endDate=2021-06-10T17%3A50%3A35.726Z&startDate=2021-06-10T17%3A48%3A00.000Z&success=0

TESTING:
Here are two runs of the generated job. One failing (https://www.openfn.org/projects/p5x4g4/runs/rn5j6xed), one succeeding (https://www.openfn.org/projects/p5x4g4/runs/rbgzbpx5)

It is failing because in `WCSPROGRAMS__KoboDataset`we try to insert `LastUpdatedAt`which is a data type `timestamp`. Now `timestamp` doest not mean the same thing for mssql and postgresql. In mssql you CANNOT update/insert a timestamp it is done automatically thus the failing. 

Is it possible that wcs come back to us with maybe another datatype to use, or something else. In the meantime Im also thinking of a workaround.

ps: it succeeds when I comment out that operation.

**Comment by aleksa-krolls** [comment]
@lakhassane Can we use the `datetime` data type? https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver15

**Comment by lakhassane** [comment]
I tried and it seems to work. So the same insert query work for both sql server (datetime) an postgres (timestamp).
Im making the change on the job and push again

**Comment by lakhassane** [comment]
So you should be good to go whenever

**Comment by dianedetoeuf** [comment]
Great, thanks a lot!

**Comment by dianedetoeuf** [comment]
hmm I'm running A1 but A3 doesn't seem to be going...

**Comment by aleksa-krolls** [comment]
@dianedetoeuf Clear state in Job 1 and try again: https://www.openfn.org/projects/p5x4g4/jobs/jyd8gg

(We've been testing with this, so OpenFn sees that the Kobo form hasn't changed since the last run and is therefore not doing anything... so if you clear state on this job - see trashcan icon - and run again, this will reset.)

Then, you'll see two A3 runs now... one for Postgres and one for Mssql. You can share the link to the Mssql one with Steve and Jonathan to run the sql in the DB and verify or adjust the output. This will be great to have their eyes on it to confirm the data model is also outputting as they expect.

**Comment by dianedetoeuf** [comment]
Thanks. How do I get the table names to start with WCSPROGRAMS? I've tried putting that into p1 and tableID but it doesn't appear.

**Comment by aleksa-krolls** [comment]
@dianedetoeuf so p1 + p2 + tableId make up the table name... so try this...
```
{ uid: 'apZrpKcK78xzrPcAfRrfac', p1:'WCSPROGRAMS', p2: '', tableId: 'SharksRays'},
```

**Comment by dianedetoeuf** [comment]
Hmm with that the table name I get is "wcsprograms_formgroup_surveytype"

**Comment by aleksa-krolls** [comment]
@daissatou2 Ah, so remember this script is creating lots of tables, including reference tables to capture the Kobo choices like SurveyType, District, etc. Therefore, to know these reference tables belong to this form... I'd recommend that we actually leverage `p2` to say `Sharks` or `SharksRays` so that you know that these reference tables belong to this form. 

@lakhassane fyi, looks like if no `p2` is specified, the default is `FormGroup`... can we return nothing if no p2 is specified? We can discuss on Monday.

**Comment by lakhassane** [comment]
@lakhassane done for `p2` @aleksa-krolls
